/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    FullDayTable: typeof import('./components/FullDayTable.vue')['default']
    LegendPanel: typeof import('./components/LegendPanel.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    QueryFilters: typeof import('./components/QueryFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/SelectField.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    StatusNotice: typeof import('./components/StatusNotice.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTag: typeof import('vant/es')['Tag']
  }
}
